<?php

namespace App\Entity\Registration;

use App\Entity\Core\Informant;
use App\Entity\Core\Site;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as GEDMO;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Registration\SelfRegistrationRepository")
 */
class SelfRegistration
{

    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @ORM\Column(type="string")
     */
    private string $name;

    /**
     * @ORM\Column(type="string")
     * @Assert\Regex (pattern="/^[+][0-9]{6,}$/", message="The value should begin with + and have at least 6 numbers")
     */
    private string $phoneNumber;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Site")
     * @ORM\JoinColumn(name="FK_siteId", referencedColumnName="id", nullable=false)
     */
    private Site $site;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Informant")
     * @ORM\JoinColumn(name="FK_informantId", referencedColumnName="id", nullable=true)
     */
    private ?Informant $informant;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private int $status;

    /**
     * @var \DateTime
     * @GEDMO\Timestampable(on="change", field={"status"})
     * @ORM\Column(type="datetime")
     */
    private \DateTime $statusDate;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $clientIP = null;

    public ?int $site_1 = null;
    public ?int $site_2 = null;
    public ?int $site_3 = null;
    public ?int $site_4 = null;
    public ?int $site_5 = null;
    public ?int $site_6 = null;
    public ?int $site_7 = null;
    public ?int $site_8 = null;
    public ?int $site_9 = null;
    public ?int $site_10 = null;


    public function __construct()
    {
        $this->status = SelfRegistrationStatus::STATUS_NEW;
        $this->statusDate = new \DateTime();
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * @param string $phoneNumber
     */
    public function setPhoneNumber(string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * @return Site|null
     */
    public function getSite(): ?Site
    {
        return $this->site;
    }

    /**
     * @param Site|null $site
     */
    public function setSite(?Site $site): void
    {
        $this->site = $site;
    }

    /**
     * @return Informant|null
     */
    public function getInformant(): ?Informant
    {
        return $this->informant;
    }

    /**
     * @param Informant|null $informant
     */
    public function setInformant(?Informant $informant): void
    {
        $this->informant = $informant;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return \DateTime
     */
    public function getStatusDate(): \DateTime
    {
        return $this->statusDate;
    }

    /**
     * @param \DateTime $statusDate
     */
    public function setStatusDate(\DateTime $statusDate): void
    {
        $this->statusDate = $statusDate;
    }

    /**
     * @return string|null
     */
    public function getClientIP(): ?string
    {
        return $this->clientIP;
    }

    /**
     * @param string|null $clientIP
     */
    public function setClientIP(?string $clientIP): void
    {
        $this->clientIP = $clientIP;
    }

    /**
     * @return int|null
     */
    public function getSite1(): ?int
    {
        return $this->site_1;
    }

    /**
     * @param int|null $site_1
     */
    public function setSite1(?int $site_1): void
    {
        $this->site_1 = $site_1;
    }

    /**
     * @return int|null
     */
    public function getSite2(): ?int
    {
        return $this->site_2;
    }

    /**
     * @param int|null $site_2
     */
    public function setSite2(?int $site_2): void
    {
        $this->site_2 = $site_2;
    }

    /**
     * @return int|null
     */
    public function getSite3(): ?int
    {
        return $this->site_3;
    }

    /**
     * @param int|null $site_3
     */
    public function setSite3(?int $site_3): void
    {
        $this->site_3 = $site_3;
    }

    /**
     * @return int|null
     */
    public function getSite4(): ?int
    {
        return $this->site_4;
    }

    /**
     * @param int|null $site_4
     */
    public function setSite4(?int $site_4): void
    {
        $this->site_4 = $site_4;
    }

    /**
     * @return int|null
     */
    public function getSite5(): ?int
    {
        return $this->site_5;
    }

    /**
     * @param int|null $site_5
     */
    public function setSite5(?int $site_5): void
    {
        $this->site_5 = $site_5;
    }

    /**
     * @return int|null
     */
    public function getSite6(): ?int
    {
        return $this->site_6;
    }

    /**
     * @param int|null $site_6
     */
    public function setSite6(?int $site_6): void
    {
        $this->site_6 = $site_6;
    }

    /**
     * @return int|null
     */
    public function getSite7(): ?int
    {
        return $this->site_7;
    }

    /**
     * @param int|null $site_7
     */
    public function setSite7(?int $site_7): void
    {
        $this->site_7 = $site_7;
    }

    /**
     * @return int|null
     */
    public function getSite8(): ?int
    {
        return $this->site_8;
    }

    /**
     * @param int|null $site_8
     */
    public function setSite8(?int $site_8): void
    {
        $this->site_8 = $site_8;
    }

    /**
     * @return int|null
     */
    public function getSite9(): ?int
    {
        return $this->site_9;
    }

    /**
     * @param int|null $site_9
     */
    public function setSite9(?int $site_9): void
    {
        $this->site_9 = $site_9;
    }

    /**
     * @return int|null
     */
    public function getSite10(): ?int
    {
        return $this->site_10;
    }

    /**
     * @param int|null $site_10
     */
    public function setSite10(?int $site_10): void
    {
        $this->site_10 = $site_10;
    }

    public function getLastSiteId()
    {
        $lastSiteId = null ;
        for($i=1; $i<10;$i++) {
            if ($this->{'site_'.$i} != null) {
                $lastSiteId = $this->{'site_' . $i};
            }
        }
        return $lastSiteId;
    }
}
