<?php

namespace App\Entity\Gateway;

use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Gateway\GatewayAlertRepository")
 */
class GatewayAlert
{
    use IdentifierAutogeneratedTrait;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $gatewayNumber;

    /**
     * @ORM\Column(type="datetime")
     */
    private $notificationDate;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $lastMessage;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $errorCode;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $recoveryDone;

    public function getGatewayNumber(): string
    {
        return $this->gatewayNumber;
    }

    public function setGatewayNumber(string $gatewayNumber): void
    {
        $this->gatewayNumber = $gatewayNumber;
    }

    /**
     * @return mixed
     */
    public function getNotificationDate()
    {
        return $this->notificationDate;
    }

    /**
     * @param mixed $notificationDate
     */
    public function setNotificationDate($notificationDate): void
    {
        $this->notificationDate = $notificationDate;
    }

    /**
     * @return mixed
     */
    public function getLastMessage()
    {
        return $this->lastMessage;
    }

    /**
     * @param mixed $lastMessage
     */
    public function setLastMessage($lastMessage): void
    {
        $this->lastMessage = $lastMessage;
    }

    /**
     * @return mixed
     */
    public function getErrorCode()
    {
        return $this->errorCode;
    }

    /**
     * @param mixed $errorCode
     */
    public function setErrorCode($errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * @return bool
     */
    public function getRecoveryDone()
    {
        return $this->recoveryDone;
    }

    public function setRecoveryDone(bool $recoveryDone): void
    {
        $this->recoveryDone = $recoveryDone;
    }
}
