<?php

namespace App\Entity\Investigation;

use App\Entity\Field\FieldDataType;
use App\Entity\Investigation\Configuration\InvestigationConfiguration;
use App\Entity\Investigation\Fields\InvestigationGenericField;
use App\Entity\Investigation\Fields\InvestigationTechnicalField;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * Class InvestigationField.
 *
 * @ORM\Entity(repositoryClass="App\Repository\Investigation\InvestigationFieldRepository")
 * @ORM\Table(name="investigation_field", uniqueConstraints=
 *   { @ORM\UniqueConstraint(name="investigation_field_udx", columns={"name", "FK_investigationConfigurationId", "FK_investigationTechnicalFieldId", "FK_investigationGenericFieldId"}) }
 * )
 */
class InvestigationField
{
    use IdentifierAutogeneratedTrait;
    use TimestampableEntity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Investigation\Configuration\InvestigationConfiguration", inversedBy="investigationFields")
     * @ORM\JoinColumn(name="FK_investigationConfigurationId", referencedColumnName="id")
     */
    private InvestigationConfiguration $investigationConfiguration;

    /**
     * @ORM\Column(type="string")
     */
    private string $name;

    /**
     * @var ?string
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $description;

    /**
     * @var ?InvestigationTechnicalField
     * @ORM\ManyToOne(targetEntity="App\Entity\Investigation\Fields\InvestigationTechnicalField")
     * @ORM\JoinColumn(name="FK_investigationTechnicalFieldId", referencedColumnName="id")
     */
    private ?InvestigationTechnicalField $investigationTechnicalField;

    /**
     * @var ?InvestigationGenericField
     * @ORM\ManyToOne(targetEntity="App\Entity\Investigation\Fields\InvestigationGenericField")
     * @ORM\JoinColumn(name="FK_investigationGenericFieldId", referencedColumnName="id")
     */
    private ?InvestigationGenericField $investigationGenericField;

    /**
     * @var ?FieldDataType
     * @ORM\ManyToOne(targetEntity="App\Entity\Field\FieldDataType")
     * @ORM\JoinColumn(name="FK_fieldDataTypeId", referencedColumnName="id")
     */
    private ?FieldDataType $fieldDataType;

    public function getInvestigationConfiguration(): InvestigationConfiguration
    {
        return $this->investigationConfiguration;
    }

    public function setInvestigationConfiguration(InvestigationConfiguration $investigationConfiguration): void
    {
        $this->investigationConfiguration = $investigationConfiguration;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    public function getInvestigationTechnicalField(): ?InvestigationTechnicalField
    {
        return $this->investigationTechnicalField;
    }

    public function setInvestigationTechnicalField(?InvestigationTechnicalField $investigationTechnicalField): void
    {
        $this->investigationTechnicalField = $investigationTechnicalField;
    }

    public function getInvestigationGenericField(): ?InvestigationGenericField
    {
        return $this->investigationGenericField;
    }

    public function setInvestigationGenericField(?InvestigationGenericField $investigationGenericField): void
    {
        $this->investigationGenericField = $investigationGenericField;
    }

    public function getFieldDataType(): ?FieldDataType
    {
        return $this->fieldDataType;
    }

    public function setFieldDataType(?FieldDataType $fieldDataType): void
    {
        $this->fieldDataType = $fieldDataType;
    }
}
