<?php

namespace App\Entity\Indicator\Scope;

use App\Entity\Security\User;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Indicator\Scope\IndicatorScopeGroupRepository")
 */
class IndicatorScopeGroup
{
    use IdentifierAutogeneratedTrait;

    /**
     * @ORM\Column(type="string")
     */
    private string $name;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="App\Entity\Security\User")
     * @ORM\JoinColumn(name="FK_userId", referencedColumnName="id")
     */
    private $user;

    /**
     * @var IndicatorScopeGroupTabMembership[]
     * @ORM\OneToMany(targetEntity="IndicatorScopeGroupTabMembership", mappedBy="indicatorScopeGroup")
     */
    private $indicatorScopeGroupTabMemberships;
}
