<?php

namespace App\Entity\Fhir;

use App\Entity\Core\Site;
use App\Entity\Disease\Disease;
use App\Entity\Investigation\Investigation;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\Fhir\FhirInvestigationRepository")
 */
class FhirInvestigation
{
    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false, options={"default" = 0})
     */
    private int $status;

    /**
     * @var ?integer
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $investigationId = null;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $identifier = null;

    /**
     * @var ?array
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $jsonData;

    /**
     * @var ?array
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $responseData = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Site")
     * @ORM\JoinColumn(name="FK_siteId", referencedColumnName="id")
     */
    private ?Site $site = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Disease\Disease")
     * @ORM\JoinColumn(name="FK_diseaseId", referencedColumnName="id")
     */
    private ?Disease $disease = null;

    public function __construct()
    {
        $this->status = FhirInvestigationStatus::STATUS_NEW;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return int|null
     */
    public function getInvestigationId(): ?int
    {
        return $this->investigationId;
    }

    /**
     * @param int|null $investigationId
     */
    public function setInvestigationId(?int $investigationId): void
    {
        $this->investigationId = $investigationId;
    }

    /**
     * @return string
     */
    public function getIdentifier(): ?string
    {
        return $this->identifier;
    }

    /**
     * @param ?string $identifier
     */
    public function setIdentifier(?string $identifier): void
    {
        $this->identifier = $identifier;
    }

    /**
     * @return Site|null
     */
    public function getSite(): ?Site
    {
        return $this->site;
    }

    /**
     * @param Site|null $site
     */
    public function setSite(?Site $site): void
    {
        $this->site = $site;
    }

    /**
     * @return Disease|null
     */
    public function getDisease(): ?Disease
    {
        return $this->disease;
    }

    /**
     * @param Disease|null $disease
     */
    public function setDisease(?Disease $disease): void
    {
        $this->disease = $disease;
    }

    /**
     * @return array|null
     */
    public function getJsonData(): ?array
    {
        return $this->jsonData;
    }

    /**
     * @param array|null $jsonData
     */
    public function setJsonData(?array $jsonData): void
    {
        $this->jsonData = $jsonData;
    }

    /**
     * @return array|null
     */
    public function getResponseData(): ?array
    {
        return $this->responseData;
    }

    /**
     * @param array|null $responseData
     */
    public function setResponseData(?array $responseData): void
    {
        $this->responseData = $responseData;
    }
}
