<?php

namespace App\Entity\Fhir;

use App\Entity\Core\Site;
use App\Entity\Disease\Disease;
use App\Entity\Investigation\Configuration\InvestigationConfiguration;
use App\Entity\Submission\AndiSubmission;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\Fhir\FhirCaseRepository")
 */
class FhirCase
{
    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false, options={"default" = 0})
     */
    private int $status;

    /**
     * @var integer
     * @ORM\Column(type="integer", nullable=false)
     */
    private int $submissionId;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Investigation\Configuration\InvestigationConfiguration")
     * @ORM\JoinColumn(name="FK_investigationConfigurationId", referencedColumnName="id", nullable=false)
     */
    private InvestigationConfiguration $investigationConfiguration;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Disease\Disease")
     * @ORM\JoinColumn(name="FK_diseaseId", referencedColumnName="id")
     */
    private Disease $disease;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Site")
     * @ORM\JoinColumn(name="FK_siteId", referencedColumnName="id")
     */
    private Site $site;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private string $identifier;

    /**
     * @var ?array
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $jsonData;

    /**
     * @var ?array
     * @ORM\Column(type="json", nullable=true)
     */
    private ?array $responseData = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $comments = null;

    public function __construct()
    {
        $this->status = FhirCaseStatus::STATUS_NEW;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return int
     */
    public function getSubmissionId(): int
    {
        return $this->submissionId;
    }

    /**
     * @param int $submissionId
     */
    public function setSubmissionId(int $submissionId): void
    {
        $this->submissionId = $submissionId;
    }

    /**
     * @return InvestigationConfiguration
     */
    public function getInvestigationConfiguration(): InvestigationConfiguration
    {
        return $this->investigationConfiguration;
    }

    /**
     * @param InvestigationConfiguration $investigationConfiguration
     */
    public function setInvestigationConfiguration(InvestigationConfiguration $investigationConfiguration): void
    {
        $this->investigationConfiguration = $investigationConfiguration;
    }

    /**
     * @return Disease
     */
    public function getDisease(): Disease
    {
        return $this->disease;
    }

    /**
     * @param Disease $disease
     */
    public function setDisease(Disease $disease): void
    {
        $this->disease = $disease;
    }

    /**
     * @return Site
     */
    public function getSite(): Site
    {
        return $this->site;
    }

    /**
     * @param Site $site
     */
    public function setSite(Site $site): void
    {
        $this->site = $site;
    }

    /**
     * @return string
     */
    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    /**
     * @param string $identifier
     */
    public function setIdentifier(string $identifier): void
    {
        $this->identifier = $identifier;
    }

    /**
     * @return array|null
     */
    public function getJsonData(): ?array
    {
        return $this->jsonData;
    }

    /**
     * @param array|null $jsonData
     */
    public function setJsonData(?array $jsonData): void
    {
        $this->jsonData = $jsonData;
    }

    /**
     * @return array|null
     */
    public function getResponseData(): ?array
    {
        return $this->responseData;
    }

    /**
     * @param array|null $responseData
     */
    public function setResponseData(?array $responseData): void
    {
        $this->responseData = $responseData;
    }

    /**
     * @return string|null
     */
    public function getComments(): ?string
    {
        return $this->comments;
    }

    /**
     * @param string|null $comments
     */
    public function setComments(?string $comments): void
    {
        $this->comments = $comments;
    }

}
