<?php

namespace App\Entity\Logs;

use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Logs\LogRepository")
 * @ORM\Table(
 *     indexes={
 *      @ORM\Index(columns={"session_id"}),
 *      }
 *  )
 */
class Log
{
    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $source;

    /**
     * @var LogLevel
     * @ORM\ManyToOne(targetEntity="LogLevel")
     * @ORM\JoinColumn(name="FK_logLevelId", referencedColumnName="id")
     */
    private $logLevel;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sessionId;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $message;
}
