<?php

namespace App\Entity\Message\SMS\Config;

use App\Entity\Core\Informant;
use App\Entity\Message\SMS\IncomingSMS;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Message\SMS\Config\AckConfigSMSRepository")
 */
class AckConfigSMS
{
    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private int $ackSmsId;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private string $phoneNumber;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private string $gatewayNumber;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private string $encryptMessage;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private string $decryptMessage;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private int $errorCode;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Informant")
     * @ORM\JoinColumn(name="FK_informantId", referencedColumnName="id")
     */
    private ?Informant $informant;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Message\SMS\Config\ConfigSMS")
     * @ORM\JoinColumn(name="FK_configSmsId", referencedColumnName="id")
     */
    private ?ConfigSMS $configSms;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Message\SMS\IncomingSMS")
     * @ORM\JoinColumn(name="FK_incomingSmsId", referencedColumnName="id", nullable=false)
     */
    private IncomingSMS $incomingSMS;

    public function __construct(int $ackSmsId,
                                string $phoneNumber,
                                string $gatewayNumber,
                                string $encryptMessage,
                                string $decryptMessage,
                                int $errorCode,
                                IncomingSMS $incomingSMS,
                                ?Informant $informant)
    {
        $this->ackSmsId = $ackSmsId;
        $this->phoneNumber = $phoneNumber;
        $this->gatewayNumber = $gatewayNumber;
        $this->encryptMessage = $encryptMessage;
        $this->decryptMessage = $decryptMessage;
        $this->errorCode = $errorCode;
        $this->informant = $informant;
        $this->incomingSMS = $incomingSMS;
    }

    public function getAckSmsId(): int
    {
        return $this->ackSmsId;
    }

    public function getInformant(): ?Informant
    {
        return $this->informant;
    }

    public function setConfigSms(?ConfigSMS $configSms): void
    {
        $this->configSms = $configSms;
    }

    public function isValid(): bool
    {
        return $this->errorCode === AckConfigSMSCode::NO_ERROR;
    }
}
