<?php

namespace App\Entity\Message\SMS;

use App\Entity\Core\Informant;
use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * Class IncomingSMS.
 *
 * @ORM\Entity(repositoryClass="App\Repository\Message\SMS\IncomingSmsRepository")
 */
class IncomingSMS
{
    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $phoneNumber;

    /**
     * @var ?string
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $message = null;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $gatewayNumber;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false, options={"default" = 0})
     */
    private int $status;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=false, options={"default" = 0})
     */
    private int $type;

    /**
     * @var ?string
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $comments = null;

    /**
     * @var ?Informant
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Informant")
     * @ORM\JoinColumn(name="FK_contactId", referencedColumnName="id", nullable=true)
     */
    private ?Informant $informant = null;

    /**
     * @var bool
     * @ORM\Column(type="boolean", nullable=true)
     */
    private ?bool $pending = null;

    /**
     * @return string
     */
    public function getPhoneNumber(): string
    {
        return $this->phoneNumber;
    }

    /**
     * @param string $phoneNumber
     */
    public function setPhoneNumber(string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * @return string|null
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * @param string|null $message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * @return string
     */
    public function getGatewayNumber(): string
    {
        return $this->gatewayNumber;
    }

    /**
     * @param string $gatewayNumber
     */
    public function setGatewayNumber(string $gatewayNumber): void
    {
        $this->gatewayNumber = $gatewayNumber;
    }

    /**
     * @return int
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * @return int
     */
    public function getType(): int
    {
        return $this->type;
    }

    /**
     * @param int $type
     */
    public function setType(int $type): void
    {
        $this->type = $type;
    }

    /**
     * @return string|null
     */
    public function getComments(): ?string
    {
        return $this->comments;
    }

    /**
     * @param string|null $comments
     */
    public function setComments(?string $comments): void
    {
        $this->comments = $comments;
    }

    /**
     * @return Informant|null
     */
    public function getInformant(): ?Informant
    {
        return $this->informant;
    }

    /**
     * @param Informant|null $informant
     */
    public function setInformant(?Informant $informant): void
    {
        $this->informant = $informant;
    }

    /**
     * @return bool
     */
    public function isPending(): ?bool
    {
        return $this->pending;
    }

    /**
     * @param bool $pending
     */
    public function setPending(?bool $pending): void
    {
        $this->pending = $pending;
    }
}
