<?php

namespace App\Entity\Message\SMS;

use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * Class OutgoingSMS.
 *
 * @ORM\Entity(repositoryClass="App\Repository\Message\SMS\OutgoingSmsRepository")
 * @ORM\Table(
 *   indexes={
 *      @ORM\Index(columns={"phone_number"})
 *  }
 * )
 */
class OutgoingSMS
{
    use TimestampableEntity;
    use IdentifierAutogeneratedTrait;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="text", nullable=false)
     */
    private $message;

    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $gatewayNumber;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $pending;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?\DateTime $sent;

    /**
     * @ORM\Column(type="integer", nullable=false, options={"default" = 0})
     */
    private $failure;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $cancelled;

    public function __construct()
    {
        $this->setFailure(0);
    }

    /**
     * @return mixed
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * @param mixed $phoneNumber
     */
    public function setPhoneNumber($phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * @return mixed
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @param mixed $message
     */
    public function setMessage($message): void
    {
        $this->message = $message;
    }

    /**
     * @return mixed
     */
    public function getGatewayNumber()
    {
        return $this->gatewayNumber;
    }

    /**
     * @param mixed $gatewayNumber
     */
    public function setGatewayNumber($gatewayNumber): void
    {
        $this->gatewayNumber = $gatewayNumber;
    }

    /**
     * @return mixed
     */
    public function getPending()
    {
        return $this->pending;
    }

    /**
     * @param mixed $pending
     */
    public function setPending($pending): void
    {
        $this->pending = $pending;
    }

    /**
     * @return ?\DateTime
     */
    public function getSent(): ?\DateTime
    {
        return $this->sent;
    }

    /**
     * @param ?\DateTime $sent
     */
    public function setSent(?\DateTime $sent): void
    {
        $this->sent = $sent;
    }

    /**
     * @return mixed
     */
    public function getFailure()
    {
        return $this->failure;
    }

    /**
     * @param mixed $failure
     */
    public function setFailure($failure): void
    {
        $this->failure = $failure;
    }

    /**
     * @return mixed
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param mixed $comments
     */
    public function setComments($comments): void
    {
        $this->comments = $comments;
    }

    /**
     * @return mixed
     */
    public function getCancelled()
    {
        return $this->cancelled;
    }

    /**
     * @param mixed $cancelled
     */
    public function setCancelled($cancelled): void
    {
        $this->cancelled = $cancelled;
    }
}
