<?php

namespace App\Entity\Core;

use App\Entity\Traits\IdentifierAutogeneratedTrait;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Class Contact.
 *
 * @ORM\InheritanceType("TABLE_PER_CLASS")
 *
 * @UniqueEntity(fields="name", message="This name already exists")
 * @UniqueEntity(fields="code", message="This code already exists")
 */
abstract class ContactType
{
    use IdentifierAutogeneratedTrait;

    /**
     * @ORM\Column(type="string", nullable=false, unique=true)
     */
    protected string $code;

    /**
     * @ORM\Column(type="string", nullable=false, unique=true)
     */
    protected string $name;

    /**
     * @var ?string
     * @ORM\Column(type="string")
     */
    protected ?string $translationKey;

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getTranslationKey(): ?string
    {
        return $this->translationKey;
    }

    public function setTranslationKey(?string $translationKey): void
    {
        $this->translationKey = $translationKey;
    }

    public function __toString(): string
    {
        return $this->getName();
    }
}
